Acrescentando branch de Cadastro a Main
ALCM-bit/TechChalange_ControleDePedidos pull request #6
Opened 2024-05-12 18:05 UTC by ALCM-bit

Acrescentando branch de Cadastro a Main

2024-05-15 03:38 UTC, ericdss requested changes

2024-05-15 03:38 UTC, ericdss commented on src/ControlePedidos.API/Properties/launchSettings.json
Remover credenciais do banco de dados e deixar configuração padrão

Ex: mongodb://USER:PASS@localhost:27017/?authSource=admin&retryWrites=false&tls=false

2024-05-15 03:38 UTC, ericdss commented on src/ControlePedidos.API/appsettings.json
> +    "ControlePedidosDB": "mongodb+srv://falcmbit:56tzCdzo1CdlOqfs@teste.ypd33wu.mongodb.net/"
```suggestion
    "ControlePedidosDB": "%ConnectionStrings__ControlePedidosDB%"
```

2024-05-15 03:38 UTC, ericdss commented on src/Modules/Cadastro/ControlePedidos.Cadastro.Application/Abstractions/ICadastroService.cs
Remover imports não utilizados

2024-05-15 03:38 UTC, ericdss commented on src/ControlePedidos.API/ControlePedidos.API.csproj
> +    <PackageReference Include="AspNetCore.HealthChecks.MongoDb" Version="8.0.1" />
Remover pacote -> API não deveria ter dependências do pacote do banco de dados

2024-05-15 03:38 UTC, ericdss commented on src/Modules/Cadastro/ControlePedidos.Cadastro.Domain/Entities/Cadastro.cs
> +        public string Nome { get; set; }
Sugestão: Nome poderia ser um ValueObject, visto que, normalmente, é composto por Primeiro Nome e Sobrenome

2024-05-15 03:38 UTC, ericdss commented on src/Modules/Cadastro/ControlePedidos.Cadastro.Domain/Entities/Cadastro.cs
> +            }
ValueObjects deveriam se autovalidar, não sendo responsabilidade da entidade

2024-05-15 03:38 UTC, ericdss commented on src/Modules/Cadastro/ControlePedidos.Cadastro.Infrastructure/Repositories/Persistence/CadastroRepository.cs
> +                cadastroModel.CPF = cadastroModel.CPF.Trim().Replace(".", "").Replace("-", "");
Repositório não deveria fazer esse tipo de validação

2024-05-15 03:38 UTC, ericdss commented on src/Modules/Cadastro/ControlePedidos.Cadastro.Infrastructure/Repositories/Persistence/CadastroRepository.cs
Remover try catch dos métodos -> Não faz sentido lançar uma nova exception com a mesma mensagem de erro, pois, ao relançar a exceção, o stack trace é perdido.

Se a intenção for esconder/filtrar erros internos (ex: conexão com o database), o ideal seria capturar e fazer o throw com uma exception personalizada que identifique melhor o erro, sem expor nenhum dado. Como neste caso não há tratativa nenhuma, apenas remover.

2024-05-15 03:38 UTC, ericdss commented on src/Modules/Common/ControlePedidos.Common/Entities/RetornoPadrao.cs
Remover classe inutilizada

2024-05-15 03:38 UTC, ericdss commented on src/Modules/Common/ControlePedidos.Common/Entities/ValueObjectBase.cs
Manter nome anterior: `ValueObject`

2024-05-15 03:38 UTC, ericdss commented on src/ControlePedidos.API/Controllers/CadastrosController.cs
> +        }
```suggestion
        try
        {
            var cadastro = await _cadastroService.ObterCadastroAsync(cadastro.CPF);

            if (cadastro is not null)
            {
                return Conflict(new { error = "Cadastro já existente." });
            }

            await _cadastroService.CadastrarAsync(cadastro);

            return Created();
        }
```

2024-05-15 03:38 UTC, ericdss commented on src/ControlePedidos.API/Controllers/CadastrosController.cs
> +        }
1 - O nome `cadastradoJaExiste` da a entender que é uma variável booleana

2 - Muitas operações no banco sendo feitas sem necessidade. Caso ocorra erro na criação do registros, o próprio banco de dados já retornada erro, não sendo necessário consultar o registro.

3 - Neste caso não seria necessário retornar o nome do cliente criado, o próprio Client (origem da request) já tem essa informação. O retorno mais apropriado seria o status HTTP 201, apenas indicando que o registro foi criado.

2024-05-15 03:38 UTC, ericdss commented on tests/Modules/Pedido/ControlePedidos.Pedido.Test.Unit/CadastroTest.cs
> +        public void Validate_Should_ThrowDomainNotificationException_When_NomeForVaziu()
```suggestion
        public void Validate_Should_ThrowDomainNotificationException_When_NomeForVazio()
```

2024-05-15 03:38 UTC, ericdss commented on tests/Modules/Pedido/ControlePedidos.Pedido.Test.Unit/CadastroTest.cs
Criar teste caso a entidade seja criada corretamente

2024-05-15 21:14 UTC, ALCM-bit commented on src/ControlePedidos.API/Properties/launchSettings.json
OK

2024-05-15 21:17 UTC, ALCM-bit commented on src/Modules/Cadastro/ControlePedidos.Cadastro.Application/Abstractions/ICadastroService.cs
Removidos

2024-05-15 21:18 UTC, ALCM-bit commented on src/ControlePedidos.API/ControlePedidos.API.csproj
> +    <PackageReference Include="AspNetCore.HealthChecks.MongoDb" Version="8.0.1" />
Removido

2024-05-15 21:19 UTC, ALCM-bit commented on src/Modules/Cadastro/ControlePedidos.Cadastro.Domain/Entities/Cadastro.cs
> +        public string Nome { get; set; }
Por enquanto vamos considerar como um campo único; conforme formos desenvolvendo podemos analisar essa necessidade.

2024-05-15 21:20 UTC, ALCM-bit commented on src/Modules/Common/ControlePedidos.Common/Entities/RetornoPadrao.cs
Removido

2024-05-15 21:27 UTC, ALCM-bit commented on src/Modules/Cadastro/ControlePedidos.Cadastro.Domain/Entities/Cadastro.cs
> +            }
Ajustado.

2024-05-15 21:30 UTC, ALCM-bit commented on src/Modules/Cadastro/ControlePedidos.Cadastro.Infrastructure/Repositories/Persistence/CadastroRepository.cs
Ok.

2024-05-15 21:31 UTC, ALCM-bit commented on src/Modules/Common/ControlePedidos.Common/Entities/ValueObjectBase.cs
Ok.

2024-05-15 22:05 UTC, ALCM-bit commented on tests/Modules/Pedido/ControlePedidos.Pedido.Test.Unit/CadastroTest.cs
Ok.

2024-05-16 20:35 UTC, ALCM-bit commented on src/Modules/Cadastro/ControlePedidos.Cadastro.Infrastructure/Repositories/Persistence/CadastroRepository.cs
> +                cadastroModel.CPF = cadastroModel.CPF.Trim().Replace(".", "").Replace("-", "");
Removido e adicionado ao ValueObject

2024-05-16 23:45 UTC, ALCM-bit commented
Reabrindo

2024-05-17 23:24 UTC, ericdss commented on tests/Modules/Pedido/ControlePedidos.Pedido.Test.Unit/ControlePedidos.Pedido.Test.Unit.csproj
> +  </ItemGroup>
Remover referências ao módulo de Cadastro

2024-05-17 23:24 UTC, ericdss commented on src/Modules/Common/ControlePedidos.Common/Exceptions/ApplicationException.cs
Nome do arquivo ficou errado. Deveria ser `ApplicationNotificationException.cs`

2024-05-17 23:24 UTC, ericdss commented on src/Modules/Common/ControlePedidos.Common/Exceptions/DomainException.cs
Nome do arquivo ficou errado. Deveria ser `DomainNotificationException.cs`

2024-05-17 23:27 UTC, ericdss commented on src/Modules/Common/ControlePedidos.Common/Exceptions/ApplicationException.cs
> +public class ApplicationErrorException : Exception
```suggestion
public class ApplicationErrorException : NotificationException
```

2024-05-17 23:30 UTC, ALCM-bit commented on tests/Modules/Pedido/ControlePedidos.Pedido.Test.Unit/ControlePedidos.Pedido.Test.Unit.csproj
> +  </ItemGroup>
Removido

2024-05-17 23:30 UTC, ALCM-bit commented on src/Modules/Common/ControlePedidos.Common/Exceptions/ApplicationException.cs
Provavelmente não tinha pego com essa mudança. Ajustado.

2024-05-17 23:31 UTC, ALCM-bit commented on src/Modules/Common/ControlePedidos.Common/Exceptions/DomainException.cs
Ajustado

2024-05-18 01:41 UTC, ericdss approved these changes

2024-05-18 01:42 UTC, merged